name: bdacaII
dependencies:
  - python=3.12
  - IPython
  - beautifulsoup4
  - dateparser
  - gensim
  - httpx
  - ipykernel
  - jupyterlab
  - lxml
  - matplotlib
  - nbformat
  - networkx
  - nltk
  - numpy<2.0
  - openpyxl
  - orjson
  - pandas
  - pillow
  - pyarrow
  - python-docx
  - regex
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - sentence-transformers
  - statsmodels
  - textblob
  - textstat
  - tqdm
  - transformers
  - unidecode
  - wikipedia-api
  - wordcloud
  - ydata-profiling
  - pip>=26.0.1
  - pip:
      - fasttext-wheel
      - mwclient
      - mwparserfromhell
      - jupyterlab
      - pdfplumber
      - torch
      - wikitextparser
